/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyCargoRouteImport } from './routes/my-cargo'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrucksIndexRouteImport } from './routes/trucks.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as TrucksNewRouteImport } from './routes/trucks.new'
import { Route as TrucksIdRouteImport } from './routes/trucks.$id'
import { Route as OrdersNewRouteImport } from './routes/orders.new'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCargoRoute = MyCargoRouteImport.update({
  id: '/my-cargo',
  path: '/my-cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucksIndexRoute = TrucksIndexRouteImport.update({
  id: '/trucks/',
  path: '/trucks/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucksNewRoute = TrucksNewRouteImport.update({
  id: '/trucks/new',
  path: '/trucks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucksIdRoute = TrucksIdRouteImport.update({
  id: '/trucks/$id',
  path: '/trucks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/my-cargo': typeof MyCargoRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/subscription': typeof SubscriptionRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/trucks/$id': typeof TrucksIdRoute
  '/trucks/new': typeof TrucksNewRoute
  '/orders/': typeof OrdersIndexRoute
  '/trucks/': typeof TrucksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/my-cargo': typeof MyCargoRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/subscription': typeof SubscriptionRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/trucks/$id': typeof TrucksIdRoute
  '/trucks/new': typeof TrucksNewRoute
  '/orders': typeof OrdersIndexRoute
  '/trucks': typeof TrucksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/my-cargo': typeof MyCargoRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/subscription': typeof SubscriptionRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/trucks/$id': typeof TrucksIdRoute
  '/trucks/new': typeof TrucksNewRoute
  '/orders/': typeof OrdersIndexRoute
  '/trucks/': typeof TrucksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/favorites'
    | '/my-cargo'
    | '/notifications'
    | '/payments'
    | '/pricing'
    | '/profile'
    | '/subscription'
    | '/orders/$id'
    | '/orders/new'
    | '/trucks/$id'
    | '/trucks/new'
    | '/orders/'
    | '/trucks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/favorites'
    | '/my-cargo'
    | '/notifications'
    | '/payments'
    | '/pricing'
    | '/profile'
    | '/subscription'
    | '/orders/$id'
    | '/orders/new'
    | '/trucks/$id'
    | '/trucks/new'
    | '/orders'
    | '/trucks'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/favorites'
    | '/my-cargo'
    | '/notifications'
    | '/payments'
    | '/pricing'
    | '/profile'
    | '/subscription'
    | '/orders/$id'
    | '/orders/new'
    | '/trucks/$id'
    | '/trucks/new'
    | '/orders/'
    | '/trucks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FavoritesRoute: typeof FavoritesRoute
  MyCargoRoute: typeof MyCargoRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  SubscriptionRoute: typeof SubscriptionRoute
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  TrucksIdRoute: typeof TrucksIdRoute
  TrucksNewRoute: typeof TrucksNewRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  TrucksIndexRoute: typeof TrucksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-cargo': {
      id: '/my-cargo'
      path: '/my-cargo'
      fullPath: '/my-cargo'
      preLoaderRoute: typeof MyCargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trucks/': {
      id: '/trucks/'
      path: '/trucks'
      fullPath: '/trucks/'
      preLoaderRoute: typeof TrucksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trucks/new': {
      id: '/trucks/new'
      path: '/trucks/new'
      fullPath: '/trucks/new'
      preLoaderRoute: typeof TrucksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trucks/$id': {
      id: '/trucks/$id'
      path: '/trucks/$id'
      fullPath: '/trucks/$id'
      preLoaderRoute: typeof TrucksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FavoritesRoute: FavoritesRoute,
  MyCargoRoute: MyCargoRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  SubscriptionRoute: SubscriptionRoute,
  OrdersIdRoute: OrdersIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  TrucksIdRoute: TrucksIdRoute,
  TrucksNewRoute: TrucksNewRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  TrucksIndexRoute: TrucksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
