/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrucksIndexRouteImport } from './routes/trucks.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as TrucksNewRouteImport } from './routes/trucks.new'
import { Route as TrucksIdRouteImport } from './routes/trucks.$id'
import { Route as OrdersNewRouteImport } from './routes/orders.new'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucksIndexRoute = TrucksIndexRouteImport.update({
  id: '/trucks/',
  path: '/trucks/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucksNewRoute = TrucksNewRouteImport.update({
  id: '/trucks/new',
  path: '/trucks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucksIdRoute = TrucksIdRouteImport.update({
  id: '/trucks/$id',
  path: '/trucks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/trucks/$id': typeof TrucksIdRoute
  '/trucks/new': typeof TrucksNewRoute
  '/orders/': typeof OrdersIndexRoute
  '/trucks/': typeof TrucksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/trucks/$id': typeof TrucksIdRoute
  '/trucks/new': typeof TrucksNewRoute
  '/orders': typeof OrdersIndexRoute
  '/trucks': typeof TrucksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/trucks/$id': typeof TrucksIdRoute
  '/trucks/new': typeof TrucksNewRoute
  '/orders/': typeof OrdersIndexRoute
  '/trucks/': typeof TrucksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/orders/$id'
    | '/orders/new'
    | '/trucks/$id'
    | '/trucks/new'
    | '/orders/'
    | '/trucks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/orders/$id'
    | '/orders/new'
    | '/trucks/$id'
    | '/trucks/new'
    | '/orders'
    | '/trucks'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/orders/$id'
    | '/orders/new'
    | '/trucks/$id'
    | '/trucks/new'
    | '/orders/'
    | '/trucks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  TrucksIdRoute: typeof TrucksIdRoute
  TrucksNewRoute: typeof TrucksNewRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  TrucksIndexRoute: typeof TrucksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trucks/': {
      id: '/trucks/'
      path: '/trucks'
      fullPath: '/trucks/'
      preLoaderRoute: typeof TrucksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trucks/new': {
      id: '/trucks/new'
      path: '/trucks/new'
      fullPath: '/trucks/new'
      preLoaderRoute: typeof TrucksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trucks/$id': {
      id: '/trucks/$id'
      path: '/trucks/$id'
      fullPath: '/trucks/$id'
      preLoaderRoute: typeof TrucksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OrdersIdRoute: OrdersIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  TrucksIdRoute: TrucksIdRoute,
  TrucksNewRoute: TrucksNewRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  TrucksIndexRoute: TrucksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
